/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Dock.h
 #	source generated by 4D Plugin Wizard
 #	Project : Dock
 #	author : miyako
 #	2025/11/17
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_DOCK_H
#define PLUGIN_DOCK_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"

#include <mutex>
#import <objc/runtime.h>
#import <AppKit/AppKit.h>

void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;
typedef PA_long32 event_id_t;

@interface

Swizzle_MainApplication_Class : NSObject <NSApplicationDelegate>
{
    
}
@end

#pragma mark -

static void Dock_SET_METHOD(PA_PluginParameters params);
static void Dock_Get_method(PA_PluginParameters params);
void DOCK_SET_BADGE(PA_PluginParameters params);
void DOCK_Get_badge(PA_PluginParameters params);
void DOCK_Bounce(PA_PluginParameters params);
void DOCK_CANCEL_BOUNCE(PA_PluginParameters params);
void DOCK_SET_ICON(PA_PluginParameters params);
void DOCK_Get_icon(PA_PluginParameters params);



#endif /* PLUGIN_DOCK_H */
